### ISSUE TITLE
D-Sheet Piling does not allow LoadType: DSHEETPILING_DETERMINED for UniformLoad and SurchargeLoad

### ISSUE THREAD

**Issue by Mbweehuizen** [Deltares/GEOLib#15]
The UniformLoad and SurchargeLoad raise a ValidationError when the LoadType is set to DSHEETPILING_DETERMINED.
This is caused by the following:

The 'UniformLoad' object uses the 'VerificationLoadSettings' object

```
class UniformLoad(BaseDataClass):
    """Uniform Load. This option is not available for SignlePileModelType.

    Args:
        name: Name of the SurchargeLoad.
        left_load: Value of the load on the left side.
        right_load: Value of the load on the right side.
        verification_load_settings: VerificationLoadSettings.
        standard_deviation_left: Standard deviation of the distribution type of the left side.
        standard_deviation_right: Standard deviation of the distribution type of the right side.
        distribution_type_left: Distribution type of the left side.
        distribution_type_right: Distribution type of the right side.
    """

    name: constr(min_length=1, max_length=50)
    left_load: float
    right_load: float
    verification_load_settings: VerificationLoadSettings = VerificationLoadSettings()
```
The VerificationLoadSettingsobject uses the 'LoadTypeFavourableUnfavourableMoment ' enum object for load type
```
class VerificationLoadSettings(BaseDataClass):
    """
    Load class for moment loads
    These options are available only if the Verification (EC7/CUR) option is selected in the Model window for the D-SheetPiling model.
    For GEOLIB the "verification" parameter should be set to True in the function DSheetPilingModel.set_model

    Args:
        duration_type: Select the duration of load application, Permanent or Variable.
        load_type: Select the type of load, Favorable or Unfavorable.
    """

    load_type: LoadTypeFavourableUnfavourableMoment = (
        LoadTypeFavourableUnfavourableMoment.FAVOURABLE
    )
    duration_type: LoadTypePermanentVariable = LoadTypePermanentVariable.PERMANENT

```

The 'LoadTypeFavourableUnfavourableMoment' object  does not allow the DSHEETPILING_DETERMINED option.
```
class LoadTypeFavourableUnfavourableMoment(IntEnum):
    FAVOURABLE = 1
    UNFAVOURABLE = 2

```

The same holds for the SurchargeLoad. In D-Sheet Piling itself, this option is allowed for Uniform and Surcharge loads:

![image](https://user-images.githubusercontent.com/95024627/176458955-0dc1a8da-aa59-4eeb-b774-8fc49883fa09.png)
